### ISSUE TITLE
update 0.4.3 is bricking peoples channels and no one is supporting the several people with issues in the telegram page

### ISSUE THREAD

**Issue by JustAGuy12345** [getumbrel/umbrel#1017]
This update needs to be retested immediately on devices of different configurations, it is clear that some users have been experiencing usability-ruining errors with this update. Being that this update is for security, it is IMPERATIVE that you do not leave the release for the bad update around for people to use. This will continue to brick more and more nodes! You need to release a NEW update that fixed these issues, TEST IT BEFORE RELEASING IT.

**Comment by JustAGuy12345** [comment]
Update: banned 3 times from telegram page for suggesting the developers test the code before releasing it on all of us as guinea pigs. I CONFIRMED from one of the devs that there was no testing done before the release.

**Comment by mayankchhabra** [comment]
The only thing added in this update was LND 0.13.3 to fix a security patch on priority. A few users panicked seeing all their payment channels offline after the update, which isn't unusual and happens every time LND is restarted. There hasn't been an instance of a single Umbrel being bricked.

> I CONFIRMED from one of the devs that there was no testing done before the release.

Testing was done for several hours on multiple Umbrel nodes and the update was pushed on priority to make sure no one loses funds because the vulnerability was exposed in the wild.

> banned 3 times from telegram page for suggesting the developers test the code before releasing it

*banned for cursing, name calling and personal attacks:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/10330103/135970980-312c4723-b3a3-40ba-ab46-b4ae882b72b7.png">
