### ISSUE TITLE
[ feature request ] ethereum full node

### ISSUE THREAD

**Issue by guizmoau** [getumbrel/umbrel#1072]
Hello umbrel,

Thanks for your great work and amazing project !!

Would it be possible to run an ETH full node ?!?
It seems to run well on RPI (https://docs.ethhub.io/using-ethereum/running-an-ethereum-node/)
There is geth or dappnode that could be used.

From a technical standpoint would it be any issue with installing either geth or dappnode in umbrel ?

**Comment by eccentricexit** [comment]
What convictions do you believe is being violated by giving users this option?

While it takes around a month to sync, you can run a full archive node (in bitcoin terms i.e. a node that audits and stores every single tx since genesis) with a raspberry pi 4. It currently takes up < 700GB of storage with [erigon](https://github.com/ledgerwatch/erigon).

By giving users this option, you are helping people opt out of centralized services.

**Comment by Strykar** [comment]
Came here to ask how easy / hard it'd be to add Ethereum and Arbitrum nodes. Bit disappointed to hear it won't be.
