### ISSUE TITLE
Sparrow fails to connect to electrs v0.9.4. 

### ISSUE THREAD

**Issue by lvnilesh** [getumbrel/umbrel#1188]
Issue:

Sparrow fails to connect to electrs v0.9.4. 

Resolution:

Downgrade electrs to v0.9.1 and Sparrow is able to connect again.

Bug seems to have been introduced in this #1184

**Comment by lukechilds** [comment]
Thanks for reporting @lvnilesh! How did you install Umbrel btw? Because electrs 0.9.4 is only in master and hasn't been shipped yet.

**Comment by lukechilds** [comment]
@lvnilesh are you able toprovide more details on exactly what isn't working and what (if any) errors you are seeing?

I'm able to connect Sparrow to electrs 0.9.4 without issue.

<img width="862" alt="Screenshot 2022-01-14 at 20 55 00" src="https://user-images.githubusercontent.com/2123375/149527123-dd552be3-928b-4d82-82ab-e7c8baded869.png">
 
Opening a wallet and loading transaction history also works as expected.

Do you have a really big wallet? Not nessasarily a large number of UTXOs right now but a large hsitory with huge number of addresses used? Often the case if you've been mixing a lot with Whirlpool. If so, this can cause electrs to struggle. Potentially there could ahve been some performance degradation introduced since 0.9.1 that doesn't affect normal users but might be affecting you if you have one of these really large wallets.

Also, have you notified the electrs/Sparrow devs of this issue?

**Comment by lvnilesh** [comment]
My wallet is not large. I installed from master branch and `sudo scripts/start`. I will switch to the latest release tag and avoid using master


In my case, sparrow just doesn't seem to connect to electrs 0.9.4
The same sparrow is able to connect to bitcoin code no problem
The same sparrow is able to connect to electrs when I downgrade to 0.9.1
