### ISSUE TITLE
Umbrel wallet recovery

### ISSUE THREAD

**Issue by captJiri** [getumbrel/umbrel#1404]
To recover funds from Umbrel SW wallet in any other new SW wallet, do i need also Output descriptors like: derivation path, script type, and gap limit .. ? And where to find it? 

Thanks.

**Comment by louneskmt** [comment]
What do you mean by SW? Samourai Wallet, Software?

**Comment by captJiri** [comment]
No i mean simply if my device Raspberry with Umbel Node SW on it is not functional any more and i wanted to recover funds from node Bitcoin and also Lightning to new device or even some different wallet perhaps some SW wallet ... 
would that and how possible? Do i need the descriptor info stated above? Thanks.

**Comment by captJiri** [comment]
Or how Umbrel recovery works ...

**Comment by captJiri** [comment]
I probably found the answer, BLIXT mobile app node wallet should restore umbrel node pretty well and easy.

**Comment by louneskmt** [comment]
Umbrel on-chain Bitcoin wallet is a LND wallet, so you can restore your seed in any LND (or LND-based) app to recover your on-chain funds. 

As for your channels, you need to save your backup file (can be found in the three dot menu of the Lightning page). In order to recover your funds by force closing your channels, you need to setup a new LND, restore your seed and then restore this backup file. 

If you didn't save your backup file (you should do this every time you open or close a channel), Umbrel automatically uploads anonymised, padded with random data and encrypted backup files to a server. Then only you can decrypt it. If you need a backup, just send us a message and we will get it for you (there is no automated way yo do that at the moment).
