### ISSUE TITLE
Tor high CPU usage

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1442]
After installing Umbrel 0.5 I noticed that every container has it's own tor server, and a main tor server for the dashboard / auth. 

This main tor server is extremely busy on my machine, it uses more CPU than any other process, even more than Bitcoin and Lightning combined.

This is really strange for several reasons:

- On previous releases this tor server never used so much CPU. It was always Bitcoin, Electrs and LND that were the top 3, now suddenly it is tor.
- This server is only used for the dashboard and for auth. But I don't even use the dashboard frequently, and when I do, it's never over tor.
- It uses MUCH more than even the bitcoin-tor-server, while you would expect Bitcoin to generate much more traffic than the dashboard.

So is there any logical explanation for this? 

When I look in the logfiles it is continously trying to connect to an onion service that does not exist, failing every time. It's address is [scrubbed] so I have no idea which one it is, but I think this causes the high CPU usage.

**Comment by nevets963** [comment]
@kroese Thanks for reporting this, I am now seeing similar behaviour and will need to investigate why. I see roughly 10% CPU utilisation for that tor container while all the other are at 0%.

**Comment by nevets963** [comment]
@kroese I've taken a closer look and the behaviour I'm seeing is expected. In v0.5 we changed the architecture so that each app would it gets own Tor container for the purpose of serving apps as Hidden Services (HS) because pre v0.5 we had a lot of issues running all the apps (all the Hidden Services) inside just 1 Tor container.

The main `tor` container however can still experience higher CPU utilisation because it also serves as a SOCKS proxy for the system and for the apps. If you're doing for example doing a Initial Block Download (IBD) atm with the Bitcoin app, then you'll see some utilisation of this main `tor` container.

I un-installed all apps, and now that container is idling. We could run a SOCKS proxy in each tor container for each app, but we wanted to minimise usage of resources needed to run Tor.

**Comment by nevets963** [comment]
I think it's the only variable left. What kind of utilisation are you seeing? On my Pi4, I was seeing ~10% utilisation and I'm currently doing a Initial Block Download (IBD) with Bitcoin.
