### ISSUE TITLE
Compute Module?

### ISSUE THREAD

**Issue by awholegnuworld** [getumbrel/umbrel#1464]
Can I install and run Umbrel on a Raspberry Pi Compute Module 4, using the eMMC as the microSD card and using a m.2 NVME drive as a USB? I have a Raspberry Pi 4 and a NVME drive currently, but it would be cheaper and faster to just get a CM4 instead. Would Umbrel work on this?

**Comment by awholegnuworld** [comment]
The CM4 would of course be connected to an I/O board.

**Comment by lukechilds** [comment]
We haven't tested Umbrel OS on CM4 but I think it should work if you're connecting your NVMe drive over USB. If you're trying to use native NVMe I don't think it'll work since we don't have any NVMe detection logic in Umbrel OS.

You could still run Umbrel on a CM4 by flashing 64 bit Pi OS and then running the Linux Umbrel install script with:

```bash
curl -L https://umbrel.sh | bash
```

Definitely worth giving Umbrel OS a shot first though, let us know how it goes!

**Comment by refazi** [comment]
> The CM4 would of course be connected to an I/O board.

There is a board that is purpose built to run a bitcoin and lightning node called [BitPiRat](https://hackaday.io/project/183430-bitpirat-computer-gen20)
A Well known Umbrel fork is working on bringing it to market in a similar fashion as Umbrel's "[The Bitcoin Machine](https://thebitcoinmachines.com/)" package
