### ISSUE TITLE
Access each app (container) through shell?

### ISSUE THREAD

**Issue by 0xCUB3** [getumbrel/umbrel#1478]
Is this possible? I'd like to configure my containers through the terminal but Umbrel doesn't offer a shell feature that I can see.

**Comment by TrezorHannes** [comment]
`$ docker ps` to find the corresponding docker container ID (1st column), then `docker exec -it <CONTAINER-ID> sh`

Is that what you're looking for?
Otherwise, you may look for each `docker-compose.yml` in the `~/umbrel/app-data/` folder. Note that those get overwritten each time you do stop / start / update

**Comment by 0xCUB3** [comment]
yes that's what I'm looking for. Thanks! I also installed portainer to have a GUI to view all of the containers.

**Comment by jaonoctus** [comment]
you could also do `sudo ./scripts/app ls-installed`

then `sudo ./scripts/app compose <APP_NAME> ps`

and finally `sudo ./scripts/app compose <APP_NAME> exec -it <SERVICE_NAME>`
