### ISSUE TITLE
Update ThunderHub to the latest version. 

### ISSUE THREAD

**Issue by sbadakhc** [getumbrel/umbrel#1480]
Would be good to update to the latest version. Lot's of nice features in release v0.13.14.
https://github.com/apotdevin/thunderhub/releases/tag/v0.13.14

**Comment by esackbauer** [comment]
I had some troubles to update. But after a restart it could update.
However I can't login anymore, seems password was resetted. I have to check and will update here.

**Comment by lukechilds** [comment]
@esackbauer does the password displayed in the Umbrel app store listing for Thunderhub not work for you?

**Comment by esackbauer** [comment]
Yes, the default password is working. It seems my manually configured password was overwritten by the update.

**Comment by lukechilds** [comment]
Ah sorry about that. We won't have overwritten any config file changes but we do now use `MASTER_PASSWORD_OVERRIDE` to set the password instead of a nasty hack we used before that was preventing us from being able to update Thunderhub. I guess this must take priority over any previous user supplied password.

https://github.com/getumbrel/umbrel-apps/blob/642a4bd52a2cfbb2431a84b1e9ea1b9a8b9d2273/thunderhub/docker-compose.yml#L19

I'll close this issue since Thunderhub is now on the latest version.
