### ISSUE TITLE
Are the developers there?How to uninstall umbrel completely?

### ISSUE THREAD

**Issue by bluehysteric** [getumbrel/umbrel#1496]
How to uninstall umbrel completely?

**Comment by ulm0** [comment]
Not sure if this is the correct way, but i just stop umbrel uninstall every app with the app script (under scripts folder) and remove the folder.

**Comment by satoshinotdead** [comment]
That's not enough, we need to erase the saved data on mounted HD.

Sorry guys but Umbrel and LN are a toy. They are hacking all the LN services on the internet because almost all pursue good UI and not security and privacy.

It's like bitcoiner scene get an big Apple on their face. You better try Ronin Dojo and Nextcloud Pi (on Raspberry OS Lite, Debian without shitty apps opened to the world).

If you browse a forum on internet, they can reach your umbrel. It's just a matter of time they get your password because you are trusting to what you see, there isn't cryptography behind your connection to your node.

That's always was a big joke.

**Comment by JimSB** [comment]
Hey y'all developers are definitely here and Umbrel is hard at work 7 days a week on a v1 release! 

All these issues are definitely heard and tracked and when accessing I advise setting up a non-SMS Two-Factor Authentication (so you don't get SIM swapped too) you can add 2FA on Umbrel today!  Thank you for all feedback.

For deleting Umbrel it installs on the root directory of wherever you ran the command and can delete the directory with the linux deletion command: 

`rm ~/Umbrel/`

This will delete all Umbrel related files.

Or prepend `~/` with the directory you installed Umbrel in - ideally Umbrel is running on its own storage drive and can also reformat the drive.  

If there's any issues you have in Linux with Docker or anything that seems to remain running or an issue feel free to make a post in the Telegram for immediate assistance! https://t.me/getumbrel/207765

**Comment by AidenWTF** [comment]
> Hey y'all developers are definitely here and Umbrel is hard at work 7 days a week on a v1 release!
> 
> All these issues are definitely heard and tracked and when accessing I advise setting up a non-SMS Two-Factor Authentication (so you don't get SIM swapped too) you can add 2FA on Umbrel today! Thank you for all feedback.
> 
> For deleting Umbrel it installs on the root directory of wherever you ran the command and can delete the directory with the linux deletion command:
> 
> `rm ~/Umbrel/`
> 
> This will delete all Umbrel related files.
> 
> Or prepend `~/` with the directory you installed Umbrel in - ideally Umbrel is running on its own storage drive and can also reformat the drive.
> 
> If there's any issues you have in Linux with Docker or anything that seems to remain running or an issue feel free to make a post in the Telegram for immediate assistance! https://t.me/getumbrel/207765

sudo rm -rf ~/umbrel/ would be correct
