### ISSUE TITLE
SD Card Health false positive in 0.5.2

### ISSUE THREAD

**Issue by levens-github** [getumbrel/umbrel#1528]
Since updating to v0.5.2 I am getting the pop up to replace my microSD card. However when running sd-card-health locally via SSH it always returns false.

`
umbrel@umbrel:~/umbrel/scripts/status $ ./sd-card-health 
false
`
[popup](https://www.dropbox.com/s/hbpw3ul44pjyzb6/popup.png?dl=0https://www.dropbox.com/s/hbpw3ul44pjyzb6/popup.png?dl=0)

**Comment by gdlfr** [comment]
Same. 
Changed microSD card from S.D. Extreme MicroSDXC 64 GB Class 10 V30 A2 UHS-I U3 to Extreme 128. 
But after automatic backup restoring both ```./sd-card-health``` respond false and popup shows again after each login in web-interface.

**Comment by IMPranshu** [comment]
I think the popup is coming whenever there is a spike in R/W speed. And in my view, this can be ignored

**Comment by inauman** [comment]
Ditto. Based on the Umbrel warning about the SD Card, I replaced it today with a new one but still getting the same warning. But this time, when I ran umbrel@umbrel:~/umbrel/scripts/status $ ./sd-card-health, it returned **false**
![Umbrel Warning MicroSD Card](https://user-images.githubusercontent.com/14142235/198916308-bfaafde8-00fc-4d79-bb0a-d354937e4351.jpg)

**Comment by nevets963** [comment]
Hey folks, I'm an engineer on the team who worked on this. The test script is based on a script from the Pi Foundation (https://github.com/raspberrypi-ui/agnostics). It definitely looks like several users are getting false positives 😞 . I've been working on a few ideas to make this more robust and will aim to get this released ASAP.

**Comment by IMPranshu** [comment]
> Hey folks, I'm an engineer on the team who worked on this. The test script is based on a script from the Pi Foundation (https://github.com/raspberrypi-ui/agnostics). It definitely looks like several users are getting false positives disappointed . I've been working on a few ideas to make this more robust and will aim to get this released ASAP.

Would love to help with this. I have some idea on how to provide better suggestions

**Comment by Zrce** [comment]
Returning "true" means the SD card is fine?

**Comment by nevets963** [comment]
We released Umbrel v0.5.3 that has disabled this check. I do apologise for any inconvience here folks!

**Comment by inauman** [comment]
Thank you @nevets963. I just updated my node to v0.5.3 and it is looking good.

**Comment by jsatur** [comment]
I started with the same issue even with v0.5.3 and updated to v0.5.4 and continues with the issue. 
also returning : umbrel@umbrel:~/umbrel/scripts/status $ ./sd-card-health  false

**Comment by nmfretz** [comment]
@jsatur this script used to be used to show SD card health warnings in the UI in v0.5.2. Since v0.5.3 we no longer do checks for this due to issues noted above, but the script remains in the codebase for now. You can ignore running this script.

**Comment by jsatur** [comment]
@nmfretz mfretz thank you

**Comment by Juniorduc44** [comment]
So what do we do? Id like to know a fix to this. Tired of buying new cards and ssd's. Is there a perfect card and SSD made to mitigate this issue. Id like to travel and not have to worry about my node needing to be baby sat every few days.

**Comment by IMPranshu** [comment]
@Juniorduc44 I understand you, man. I was in the same place last year and then I spent on a good SD card and SSD which has lasted me till now and I belive will last for next 4-5 years before needing any maintainece. For both I went with Samsung after going through a research paper where NASA is using Samsung made NAND chips for memory due to their reliability and robustness. For SD card "Samsung Pro Ultimate" and for SSD "Samsung T9 Portable" is my go to choice. They both are covered under 10 years and 5/3 years warranty respectively. 

Hope this helps you.

**Comment by Juniorduc44** [comment]
Took me some time to search the internet last night and figure out what issues others were having. Btw i love samsung for their ssds so ill look into getting the micro sd for sure.

The node went off a couple nights ago right after loading another brand new sd card. I have a monitor dedicated only for the node and i noticed it said something about a swap file error. So i ssh`ed into it and since im now a regular linux user i went straight to my fstab file. Guess what....there was no swap file at all.

Forgot how to load one so i googled it and found something on stack flow. The node crashed a couple more times because of some sort of docker or buffer issues or something, cant remember exactly but i decided to use the top function and monitor the operating system when it booted. I saw the cpu was getting overloaded and i guess i was just to hasty in trying to get the thing to update to early after bootup when using the GUI.

So its been running fine for over 24 hrs no and ill be traveling back home for a month. Seems we back to normal right on time baby!!!!!

**Comment by Juniorduc44** [comment]
Creating the swap file:

- sudo fallocate -l 4G /swapfile

Make the file only accessible to root:

- sudo chmod 600 /swapfile

Use the file as a swap space:

- sudo mkswap /swapfile

If all that works and you want to make the above changes permanent:

- sudo echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
