### ISSUE TITLE
please don't restart docker service on upgrade

### ISSUE THREAD

**Issue by ebaschiera** [getumbrel/umbrel#1537]
Hi,
I am on an Ubuntu server which runs several containers for different purpose from Umbrel.
I noticed that when upgrading Umbrel (I ran this command: `sudo ./scripts/update/update --repo getumbrel/umbrel#v0.5.3` ) Docker service is restarted. That is harmful for all the other running containers that don't deal with Umbrel.
Is it possible to avoid the service restart?

Thanks!

**Comment by nevets963** [comment]
@ebaschiera We restart the Docker daemon during the update process in order to improve the reliability of the update process itself. Some users were getting strange errors when pulling new Docker images such as:

```
ERROR: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout
```

Which although suggests some network issue, we found simply restarting the Docker daemon resolved the issue - I wish I knew why.

The only suggestion I can make atm is to apply a [restart policy](https://docs.docker.com/engine/reference/run/#restart-policies---restart) to your containers.

**Comment by louneskmt** [comment]
It may be better to watch for this error and restart the service if necessary, instead of rawly restarting it for everybody. Or find a better way to address it. Just got my dedicated server's Docker restarted, with all my other stacks (Matrix server, password manager, etc). This is not really viable haha

**Comment by mayankchhabra** [comment]
I think there are far too many Docker errors to watch and catch. Multiple times, it's the "network has active endpoints" error, then other times it's just weird Docker bugginess. I agree, the solution to restart the daemon isn't ideal, but the alternates are far too complex and might not work effectively.
