### ISSUE TITLE
Fast forward multiple versions on update

### ISSUE THREAD

**Issue by bennyhodl** [getumbrel/umbrel#1545]
I updated my Umbrel after being off for a while `v0.14.8`. It has me installing updated in succession. Would be nice to fast-forward to the current version from any previous version.

**Comment by bennyhodl** [comment]
Ok, found this on the troubleshoot page https://community.getumbrel.com/t/umbrel-troubleshooting-guide/3632

```
A. For Rasp Pi users:

Enter using SSH into your Umbrel node, then run:

cd ~/umbrel && sudo ./scripts/update/update --repo getumbrel/umbrel#v0.4.8

Replace v0.4.8 with the version you want to update to.

If the update was stuck in update, run this before the above command:

sudo rm statuses/update-in-progress
sudo rm statuses/update-status.json

Restart your node if is done OK:

sudo reboot
```

**Comment by louneskmt** [comment]
Hey! You can normally do that, but sometimes there are breaking changes in the update script or base functioning of Umbrel, that requires you to go through specific updates (introducing these changes). For example you can't go straight from <v0.4.18 to v0.5.0 because we prepared the scripts for v0.5.0 in v0.4.18. 

The dashboard will propose you directly the latest version you can update to.

**Comment by mayankchhabra** [comment]
Yes, usually it works with fast forwarding — except major updates that bring huge architectural changes like 0.5. @bennyhodl if that answers your questions, can we close this issue?

**Comment by tlindi** [comment]
> Hey! You can normally do that, but sometimes there are breaking changes in the update script or base functioning of Umbrel, that requires you to go through specific updates (introducing these changes). For example you can't go straight from <v0.4.18 to v0.5.0 because we prepared the scripts for v0.5.0 in v0.4.18.
> 
> The dashboard will propose you directly the latest version you can update to.

Mind to put this somewhere (eg installation instructions). There is lots of people looking for and offering command line update instructions. I think you should state somewhere they are not "supported". Hmmkay?

**Comment by mayankchhabra** [comment]
Thanks for the feedback @tlindi! Good suggestion, we implemented the same in the update script in a prior Umbrel release:
https://github.com/getumbrel/umbrel/blob/d6641f81ee7ef05b0b404889290cfa8ae1b03173/scripts/update/update#L76-L80

This should prevent any potential issues caused due to incompatible updates in the future.

**Comment by tlindi** [comment]
Thank You very much on behalf of all the plebs on TG Channel!
