### ISSUE TITLE
[Feature Request] Ability to change the Default Web UI port

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel#1547]
Users should have the option to change the port that is being used by Umbrel UI i.e. 80 to increase flexibility for future developments.

**Comment by mayankchhabra** [comment]
^ This is the correct way to do it. Alternatively, if you already have Umbrel running on port 80, you could do:

```
# inside umbrel directory
sudo scripts/stop

# change NGINX_PORT from 80 to something else in .env
nano .env 

sudo scripts/start
```

And Umbrel's UI will be accessible on the new port you set.

**Comment by kegesch** [comment]
Since it is not documented for > 1.0.0 versions, i will hijack this issue so that others will find it.
You can change the port for `umbreld`.

1. Login via SSH or use the terminal in the Web UI.
2. `sudo nano /etc/systemd/system/umbrel.service`
3. Add port flag in the start command e.g. `ExecStart=umbreld --port=8080 --data-directory=/home/umbrel/umbrel`
4. Save and exit the file `Ctrl+S` + `Ctrl + X`
5. Reload the system daemon `sudo systemctl daemon-reload`
6. Restart umbrel `sudo systemctl restart umbrel`

Umbrel can then be accessed at `http://umbrel.local:8080`.
