### ISSUE TITLE
Feature request - Support for multiple external drives on Raspberry Pi for NAS solutions

### ISSUE THREAD

**Issue by alexander-koval** [getumbrel/umbrel#1586]
For now, it is available to plug only one external hard drive to Raspberry Pi and this functionality hard coded to Umbrel initialization process. But it exists many different NAS solutions for Rapsberry Pi. For example Argon EON (https://www.argon40.com/products/argon-eon-pi-nas). For now this solutions can't be useful with Umbrel and it is so sad. It will be great if Umbrel team would take a look how to solve this problem and add support for multiple external drives that would be useful in NAS solutions for Raspberry Pi.

**Comment by mayankchhabra** [comment]
Hey Alex, that's definitely a great idea. Unfortunately, the default Raspberry Pi power supply isn't reliably capable of powering multiple drives at the same time. AFAIK Argon uses their own power supply which is beefier. So if we add a feature like this, there's a high likelihood that unaware users could end up with data loss/corruption due to power issues. :/

**Comment by alexander-koval** [comment]
Hi Man! I think it's different issues. The power supply is an issue of course, but you haven't has any reasons to deny users to plug another hard drive if they want. Why just not save hard drive UUID as environment variable and boot from it on startup? Not from `/dev/sda1` as it is, but from some uuid? May be this feature can be like an optional? So if someone wants to use it he can, and other people don't care about it? May be make some variables in a settings view?

**Comment by cebas** [comment]
+1 for this request.
I also don't like that the only storage I can use gets automagically formatted and used exclusivelly.
I undestand that this was planned as an usability feature for unexperienced users, but it also leave power users behind. 
I would like to have options to choose where to put the data (disk, partition or whatever).
ie: if there's no storage attached at boot time, ask for it and let me configure what I need.

**Comment by mayankchhabra** [comment]
> Why just not save hard drive UUID as environment variable and boot from it on a startup? Not from /dev/sda1 as it is, but from some uuid? May be this feature can be like an optional? So if someone wants to use it he can, and other people don't care about it?

The main issue is that, as soon as you have the Pi powering two drives, there's pretty much no guarantee that it'd be able to reliably power those two drives. So say we support booting fromthe SD instead of an SD card, it doesn't really solve the issue. Once as you connect the second drive, things might go well for a while. You'll be able to configure the second drive, expand your total storage, etc. But there's no guarantee that the Pi will able to reliably power those two drives for an extended period of time, especially if there's a lot of concurrent read-write happening all at once (eg. Bitcoin Node syncing on one drive while you're streaming something from Plex on the second drive, etc).

The fix isn't easy. Off-market Raspberry Pi power supplies open another can of worms. Eg. the CanaKit power supply, which a lot of users get out of the box with the CanaKit Pi kit, isn't even able to power a single drive reliably. All of those users have to go through a painful experience of troubleshooting their Umbrel and end up realizing that they need the official power supply.

--

Of course this wouldn't have been an issue if we didn't recommend Raspberry Pi as the default option. That being said, if you install Umbrel on Ubuntu/Debian, you also get the benefit of being able to use more than one drive, eg. you can install Umbrel on a RAID set up, expand storage on the fly, etc.

**Comment by alexander-koval** [comment]
I understand one thing. If you want to use your Raspberry Pi with Umbrel as media center, you shouldn't. Try to use other solutions for media centers. For example OpenMediaVault. And use your Raspberry as you want, without any restrictions. That I did.

**Comment by jonathandotbz** [comment]
*Alternatively you can install Umbrel on any Ubuntu or Debian system (both x86 and **arm64**)...* -README.md

I.e., could a work-around be to:
1. install Raspberry Pi OS Lite on the Argon EON,
2. install the EON scripts, then
3. install the "any Ubuntu/Debian" Linux version of Umbrel on top?

Or would there need to be some hard drive setup between steps 2. and 3. ?
