### ISSUE TITLE
Bitcoin status un-operational even when it's running

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#16]
Noticed that sometimes (especially on the first startup) `/v1/bitcoind/status` returns `{ operational: false }` even when `bitcoind` is running and even accessible via `bitcoin-cli`.

**Comment by nolim1t** [comment]
Nice find. Copy pasta mistake while adding regtest.On Tue, Jul 7, 2020 at 21:12, Mayank Chhabra <notifications@github.com> wrote:  
Turns out a mistake was made in this commit that changed the mainnet RPCPORT env variable from 8332 to 18443.
It's ok for now, but this can turn out to be a very dangerous mistake in the future. For that reason, I really suggest testing out everything on the mainnet before merging. I will also personally be more thorough in my code review.
cc: @nolim1t
