### ISSUE TITLE
Consider not enabling BIP37 for untrusted peers / not setting `-peerbloomfilters` by default in `bitcoind` settings

### ISSUE THREAD

**Issue by darosior** [getumbrel/umbrel#1624]
Serving BIP37 was made opt-out (through [BIP111](https://github.com/bitcoin/bips/blob/master/bip-0111.mediawiki)) in [Bitcoin Core 0.12 ](https://github.com/bitcoin/bitcoin/blob/47d981e8273804a040d71665a4cb16038d6717e1/doc/release-notes/release-notes-0.12.0.md#node_bloom-service-bit)and consequently opt-in in [Bitcoin Core 0.19](https://github.com/bitcoin/bitcoin/pull/16152) as [it opens up a DoS vector](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-July/017145.html).

It seems like Umbrel (and other node-in-a-box solutions) set `-peerbloomfilters` to `1` by default. It seems unadvisable to do so for listening nodes accepting connections from untrusted peers, especially since:
1. Node-in-a-box solutions are often ran on far-from-beefy hardware (Rapsbeery pis)
2. They usually come bundled with a Lightning node (for which an unavailable `bitcoind` *might* put a user's funds at risk)

Opening this issue was triggered by a proposal to [remove BIP35 support in Bitcoin Core](https://github.com/bitcoin/bitcoin/pull/27426), which led to a [contributor estimating](https://github.com/bitcoin/bitcoin/pull/27426#issuecomment-1529678174) that a large part of the listening nodes on the network have manually opted in to serve BIP35/BIP37. We eventually figured many node-in-a-box solutions do set it by default.

I'm opening this issue in order to explore:
1. The reason(s) for setting `-peerbloomfilters` to `1` by default. (I've heard Bisq needs it for instance.)
2. The alternatives to using BIP37. (For instance BIP158 filters or since you are connecting to your own node anyways you might as well just use an Electrum server?)
3. Failing that, the possibility to somehow not expose BIP37 to untrusted peers.

Thanks,
Antoine

**Comment by lukechilds** [comment]
Hey Antoine!

>It seems like Umbrel (and other node-in-a-box solutions) set -peerbloomfilters to 1 by default. It seems unadvisable to do so for listening nodes accepting connections from untrusted peers, especially since:
>
> 1. Node-in-a-box solutions are often ran on far-from-beefy hardware (Rapsbeery pis)
> 2. They usually come bundled with a Lightning node (for which an unavailable bitcoind might put a user's funds at risk)

Yep totally agree, for this reason Umbrel ships in non-listening mode. See prior discussion here: https://github.com/getumbrel/umbrel/issues/1393#issuecomment-1161592831

You can enable the Bitcoin Node app in Umbrel to accept incoming connections from Tor/I2P, but it's in advanced settings behind a warning asking the user to make sure they understand the side effects of any changes they make.

With or without `peerbloomfilters` I don't think running a listening Bitcoin node on a low powered home server inside a home network makes a lot of sense. Partly for the reasons you mention above, but also it can cause excessive bandwidth usage on the home internet connection which can also be a DoS attack vector. Trying to manage bandwidth with `maxuploadtarget` can cause new DoS attack vectors against personal clients connected over P2P.

For these reasons Umbrel has never run Bitcoin Core in listening mode by default. It was only possible before by users manually modifying config files via SSH. It's actually only very recently (in the last few months) we added the possibility to enable listening in advanced settings behind the warning.

> I'm opening this issue in order to explore:
>
> 1. The reason(s) for setting -peerbloomfilters to 1 by default. (I've heard Bisq needs it for instance.)

I believe we initially added it because some users of Blockstream Green wanted to connect it to their Umbrel and BIP37 was the only protocol Green supported (I think it might now also support Electrum?). I know we have some users using it to connect Bisq too. Bread Wallet was another one I think but not sure if that's widely used much any more.

> 2. The alternatives to using BIP37. (For instance BIP158 filters or since you are connecting to your own node anyways you might as well just use an Electrum server?)

Yep totally agree that Neutrino/Electrum make way more sense for pretty much all use cases over BIP37. To be clear Umbrel doesn't in any way use BIP37 for anything. It's just there to support client applications that need it. Almost all the locally installed Umbrel apps interface via Electrum, some via RPC and a few via P2P (but not bloom filters). I don't _think_ any local apps are using bloom filters.

Pretty much all remote clients are using Neutrino or Electrum.

> 3. Failing that, the possibility to somehow not expose BIP37 to untrusted peers.

This is already how Umbrel works by default. We don't currently have an option to toggle `peerbloomfilters` off for users that opt in to enabling incoming connections but we could definitely add that. (we only very recently shipped changing config via the UI and the initial version just included the most highly requested options, we plan to add more).

**Comment by lukechilds** [comment]
Yeah makes total sense.

Ok so we can migrate `-peerbloomfilters` to be off by default and allow users to enable it in advanced settings behind the warning to not break the rare BIP37 use cases like Green/Bisq.

> The DoS and privacy concerns aren't being overstated.

To clarify, just for my understanding, this is only when the node is publicly listening for incoming connections right? If you are behind NAT, and only connect out through Tor/I2P and do not accept incoming connections on those networks (how Umbrel functions by default) the risk is low right?

But agree, either way the risks outweigh the benefits of having it on by default since practically nothing uses BIP37 anymore.

**Comment by glozow** [comment]
Sorry for the late reply, yes, not accepting inbounds definitely lowers risk.

**Comment by lukechilds** [comment]
Hey @darosior @glozow FYI we just shipped v25.1 which includes this change 🚀

https://twitter.com/umbrel/status/1720035507592368385?s=20

`peerbloomfilters` is now disabled by default, it's possible to re-enable it in advanced settings with a note about privacy / DoS risks:

<img width="789" alt="Screenshot 2023-11-02 at 19 17 54" src="https://github.com/getumbrel/umbrel/assets/2123375/b5aba3a9-0941-41b2-896b-69ff2f340c64">


Thanks for your feedback on this, appreciate it!
