### ISSUE TITLE
Samba not connecting to any client

### ISSUE THREAD

**Issue by mathix420** [getumbrel/umbrel#1891]
Tested on windows and iOS, with tailscale and without (local-ip & umbrel.local)

**Comment by arguser** [comment]
Hey @mathix420 on Windows you won't get it working because the Samba Umbrel App doesn't run on the default Samba port, which is taken by Backup My Mac. I made it work on MacOS and Linux by being explicit on which port I want to connect to. I think they should switch the ports between those apps. 

Also, I believe this Issue should be posted to https://github.com/getumbrel/umbrel-apps/issues instead.

**Comment by mathix420** [comment]
/close

Follow there https://github.com/getumbrel/umbrel-apps/issues/1325
