### ISSUE TITLE
sudo start/stop scripts ring alarm bells

### ISSUE THREAD

**Issue by stefanwouldgo** [getumbrel/umbrel#244]
Why is this necessary? It shouldn't be.

**Comment by maltokyo** [comment]
alarm bells?

**Comment by stefanwouldgo** [comment]
In my head. Because sudo scripts can do anything to my system.

maltokyo <notifications@github.com> schrieb am Fr., 9. Okt. 2020, 01:07:

**Comment by nolim1t** [comment]
Personally think it should not need sudo to start or stop. 

Especially stop which doesn't need it.

For start there is some services which require root, but it can be just disabled if sudo isn't used.

**Comment by nioncode** [comment]
Umbrel heavily relies on docker containers, which require root to run them. You can configure your user to be able to run containers, but this effectively gives root rights to your user without needing a password and is thus not recommended (see e.g.: https://blog.zopyx.com/on-docker-security-docker-group-considered-harmful/).

Thus, I think there is no way around having to use sudo/root to start Umbrel.

**Comment by stefanwouldgo** [comment]
Oh, that's a really bad design decision in docker. One more reason for
building a docker free branch of umbrel. Another being the possibility of
running umbrel on Android and other systems that don't support docker.

Nicolas Schneider <notifications@github.com> schrieb am So., 18. Okt. 2020,
13:50:

**Comment by nolim1t** [comment]
> Umbrel heavily relies on docker containers, which require root to run them. You can configure your user to be able to run containers, but this effectively gives root rights to your user without needing a password and is thus not recommended (see e.g.: https://blog.zopyx.com/on-docker-security-docker-group-considered-harmful/).
No that is not true. The docker components do not need root at all.


> 
> Thus, I think there is no way around having to use sudo/root to start Umbrel.

There are other services which require root, but they are not really needed to start Umbrel. However some things may not work correctly. 

From a UX perspective this is bad. Considering this a a UX first approach, It might be acceptable for now.

But really those services can be probably put into a container and have "root" privileges enabled as I don't think running the start/stop script as root is really a good idea.

**Comment by lukechilds** [comment]
The start/stop script needs to be run as root because Umbrel needs to do things that requires root privileges such as start containers and shutdown/reboot the system. There is no way around this. There is nothing wrong with requiring root to start a service that requires root privileges.

What we do need to do is reduce the reliance on root and make sure only the limited parts of Umbrel that require root run as root, and that everything else is instantly dropped down to a lower privileged user when it's forked off from the start script. We've made some progress on this but there's still more in this area that needs doing before we can remove the beta label from Umbrel.

I have a note to document this in the https://github.com/getumbrel/umbrel/blob/master/SECURITY.md file to make this more clear.

>Oh, that's a really bad design decision in docker.

I don't think so. I think building Umbrel on Docker is going to be what gives it a huge competitive edge over alternatives. Docker is very popular and most existing Bitcoin applications ship Docker Compose configurations. The Umbrel application architecture is going to be based on Docker Compose, which means apps that already ship Docker Compose configurations will be trivial to port to Umbrel.

It also allows us to easily implement fine grained permission control between Umbrel applications to reduce the risk of one compromised Umbrel app compromising the entire system.
