### ISSUE TITLE
Electrs process running out of memory on testnet

### ISSUE THREAD

**Issue by thunderbiscuit** [getumbrel/umbrel#314]
Hi guys! I have been running into issues with my electrs service when I run Umbrel on testnet, and after opening an issue on the electrs repo, they suggested I bring it up here, as the setting for electrs should probably be part of the umbrel config.

[See my issue and their proposed solution here](https://github.com/romanz/electrs/issues/320).

I'm very happy with just fixing my personal config file if you think that's what's best, but I also wanted to bring it up in case it's a larger issue that other folks are running into.

**Comment by lukechilds** [comment]
See dupe issue: https://github.com/getumbrel/umbrel/issues/298

Gonna close this so we can track the conversation there and keep it in one place.

Seems like this is only an issue with custom Umbrel installs atm, potentially due to the swap we create on Umbrel OS?

Ideally this will be resolved via the upcoming `--low-memory` flag in electrs. If we get many more user reports we can look at limiting to RPC connections in Umbrel until that's shipped.
