### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by searsaw** [getumbrel/umbrel#357]
I think it'd be nice to have a native-built dark mode. Right now, I use Dark Reader, and it works perfectly fine. However, having one built-in with the app would be a nice touch in the future.

**Comment by mayankchhabra** [comment]
Thanks, @searsaw. Dark mode is definitely on our long-term roadmap. 

For now we chose not to focus on it because it can do more harm than good. Not only will the current front-end would have to be heavily refactored, but every thing added to the dashboard in the future will have to be designed twice, slowing down the pace of development.

Closing this issue now to keep things clean :)
