### ISSUE TITLE
Default configuration is not TOR ONLY

### ISSUE THREAD

**Issue by bitcoinlibre** [getumbrel/umbrel#427]
From BTC RPC Explorer App | Tools | Peers, I can see regular ip4/ip6/tor nodes connected to my node.

![imagen](https://user-images.githubusercontent.com/77515881/104787935-41c16580-5791-11eb-9ebc-da53c3a41ae9.png)

To force only tor nodes I set next parameters in bitcoin.conf and restart services
onlynet=onion
dnsseed=0
dns=0

![imagen](https://user-images.githubusercontent.com/77515881/104787952-4f76eb00-5791-11eb-95aa-f755e6904c21.png)

**Comment by louneskmt** [comment]
For a better privacy, Umbrel routes by default all the traffic via Tor, but can connect to IP v4/6 clients. This is intended.

**Comment by lukechilds** [comment]
Yeah, this is a common misconception with users.

By default Umbrel proxies all Bitcoin Core traffic through Tor. This means whether you're connecting to onion peers or clearnet peers, the connection is made over Tor. If you connect to a clearnet peer you're still anonymous, they don't see your IP, they see your Tor exit node's IP.

`onlynet=onion` just limits Bitcoin Core to only connect out to onion peers and ignore clearnet peers. That isn't much more private than connecting out to clearnet peers over Tor and it actually comes with some small risks. It makes your connections less random and could even potentially end up with two isolated independent Bitcoin networks, one on clearnet and one on Tor. Also onion addresses are cheaper than IPs to mass generate so with `onlynet=onion` you probably also slightly increase your chance of being sybil attacked.

There isn't much benefit to setting `onlynet=onion` and some tiny downsides as mentioned above so there's really no good reason to set it. That's why we don't set it in Umbrel.

**Comment by Rothschildiuk** [comment]
![Screenshot_20210226-033907](https://user-images.githubusercontent.com/15833131/109247490-522f1c00-77e4-11eb-9230-362a9cca48cf.png)
My node can't connect to any peer about 3 hours until now. What should I do?

**Comment by louneskmt** [comment]
@Rothschildiuk Open a new issue, this one is closed and your problem off topic of this one.
