### ISSUE TITLE
Umbrel dashboard auth does not apply to apps

### ISSUE THREAD

**Issue by ghost** [getumbrel/umbrel#454]
Currently the password required to enter the Umbrel UI is not actually required to use installed apps. For example, one could go directly to Specter with full access, even when the Umbrel password has not been entered.

Based on the experience, I'm guessing the intention is to close over apps so they have the same auth session as the Umbrel dashboard?

**Comment by lukechilds** [comment]
Yes, for now, during beta Umbrel makes the assumption that the local network is secure.

Long term we plan to implement automatic SSO handled transparently via Umbrel. Apps will not need to be aware of Umbrel or support SSO, we can handle it all transparently from our end.

**Comment by LaserHodl** [comment]
Totally. Figured that's where you were going with it.

Suggest keeping this ticket around for others.

**Comment by Kixunil** [comment]
@lukechilds how exactly do you intend to implement transparent SSO? I was thinking the same in my repository using nginx becuase, while current SSO works, this can be more secure (read below). Can we write the code together?

There are a few differences between our projects when it comes to handling web services but they should be minimal. The two main that come to my mind are me wanting to support multi-user setups (owner is admin who shares access to some things with e.g. family members) eventually and I would like to switch to using Unix sockets instead of TCP between Nginx and apps.

(Secure because it wouldn't allow access to possibly vulnerable Javascript/PHP/whatever crap authentication. We could just focus on security of a single service.)

**Comment by ibz** [comment]
SSO would be indeed amazing, and I also wonder how it could be implemented transparently, ie. without the apps even being aware of running on Umbrel?

I would guess that Umbrel would simulate a log in and capture the session ID / JWT cookie? Umbrel would have to proxy all requests to the app then, to inject the cookie back into the requests. In this case however, Umbrel itself would need to be aware of the app's login form in order to perform the log in in the first place?

The more interesting question is then to deal with multi-user apps. Would Umbrel also support multiple users? That would complicate things even further, but in my opinion that is a must. As @Kixunil says, the use case really is having one Umbrel per household, which has an admin and multiple users. Having a single user per Umbrel is not really interesting.

**Comment by mayankchhabra** [comment]
Hey folks, closing this now as we [introduced SSO](https://twitter.com/umbrel/status/1534164321957081093) with Umbrel 0.5.
