### ISSUE TITLE
Change default password for RTL, ThunderHub, and LiT

### ISSUE THREAD

**Issue by Kixunil** [getumbrel/umbrel#479]
The default password on these is almost worse* than default password on SSH. It should be highest priority to change it. The apps are useless otherwise.

Or better yet, implement SSO, which both RTL and ThunderHub support (IDK about LiT). Also works for btc-rpc-explorer if you ever decide to add it.

Explicit ping @lukechilds who seems to be more concerned with security.

* almost worse because it'd be trivial to pwn them if they didn't implement XSS/CSRF protections - yes I actually checked.

**Comment by AaronDewes** [comment]
> The default password on these is almost worse* than default password on SSH. It should be highest priority to change it. The apps are useless otherwise.

I know you'll say I'm not concerned about this, ..., this is a planned feature, also, you need to know the tor URL (every app has it's own) to access it, and that is not easy to get from outside.

**Comment by lukechilds** [comment]
Thanks for the ping @Kixunil.

Closing as this is a dupe of: https://github.com/getumbrel/umbrel/issues/454

>It should be highest priority to change it. The apps are useless otherwise.

I'm interested in why you think that. What exactly is the attack vector you're concerned about here?

If the user is running Umbrel on a secure network, which is the intended environment during beta, there is no issue. Apps can be accessed on a secure local network without any auth required. Apps can be accessed securely remotely via the Tor hidden service. The password auth is there as more of a pesky sibling protection.

If the user is running Umbrel on an insecure network, then yes that would be unsafe, for large number of different reasons. That's not the intended usage environment during beta.

If the attack vector you're worried about is someone malicious on the local network, using SSO does not mitigate this. All traffic is plain text HTTP so an attacker on the network could trivially listen for the SSO token and then use it to gain access.

Using a user provided password would be a pretty serious issue in my opinion since we know many users will probably re-use passwords across multiple accounts. If we allow users to set their own password we give them a false sense of security which is dangerous in itself, any attacker could listen for the password over HTTP and then replay it to gain access so it provides no real security. Not only that, but we'd be broadcasting their password in plain text over the local network which they may well also use for email/banking etc.

As documented in https://github.com/getumbrel/umbrel/issues/454#issuecomment-767389108 we have a nice solution for this we plan to implement before doing a stable release which can enable transparent SSO for all apps without them even being aware. But it's pointless doing this before we've implemented a solution for secure local communication, since it would be trivial to bypass, and low priority while the requirement is to be run on a secure network.

I realise this is only documented in a GitHub issue and it's not currently in our security document so I will update our security document to clarify that, thanks for bringing it up.

**Comment by Kixunil** [comment]
> Closing as this is a dupe of: #454

Ah, tried to find if it's opened already yet I missed that. Sorry.

> I'm interested in why you think that. What is the attack vector you're concerned about here?

Same as SSH - default password => any device including vulnerable router can pwn it. It should be obvious it leads to possibility of stealing all sats.

> which is the intended environment during beta

This is absolutely **not** clearly documented on the website. What happens today is random people downloading Umbrel not knowing about this. It's already happening today.

Being clear and honest about the state of software is pretty much industry standard. Many LN developers clearly mark LN as beta *despite being very safe and usable*. In some cases they go as far as to intentionally obscure unsafe usage from users. Even Bitcoin Core is still marked as beta. Yes I agree it's quite an extreme but what you're doing is the other extreme.

> SSO does not mitigate this

Correct, I was thinking about UX which you pride yourself about. Not having to enter redundant password is a better UX than having to enter it.

> HTTP so an attacker on the network could trivially listen

It's absolutely not as trivial as sending two POST requests to a known address. Setting up ARP poisoning and sniffer and then finding correct packet takes some time. Sending two POST requests is two lines of code.

Great that you're going to update your security document but definitely link it from website.
