### ISSUE TITLE
Making electrs optional

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel#505]
Electrs is a dependency some users might not need, and making it an optional app would make the bae a bit smaller. I think this was your original plan (From what I see in te Telegram history), and it could be the first incompatible app that does only work if the node is not pruned (Pruned nodes aren't implemented yet). Not sure if you want to implement it, but it might be good to make it an external app to 
- Make the base a bit smaller 
- Make pruned nodes easier (No crashing electrs in the background)
- Not have an app running that users might not need

**Comment by louneskmt** [comment]
I personally think it is better to keep electrs as part of the base services as :
- a lot of wallet needs an Electrum server as an intermediary and cannot connect to Core directly. Most users do not know what is Electrum Server and just wanna connect their wallet to Umbrel. 
- a couple of Umbrel apps depends on an Electrum server. We can't really ask the user to install an app in order to run another app, this is poor UX. 

But interested in @mayankchhabra and @lukechilds thoughts on this.

**Comment by jon4hz** [comment]
I would appreciate an optional electrs server or at least an option to throw it out easy. It's the process that uses by far the most CPU.

**Comment by lestephane** [comment]
You can allocate a maximum share of CPU and memory when using docker containers. 

https://github.com/compose-spec/compose-spec/blob/master/deploy.md#resources

As long as it is running unconstrained, it will cause lots of support requests, and crashes. Look at the load on mine.

![image](https://user-images.githubusercontent.com/5460884/114968432-fc3f3200-9e7e-11eb-8b95-d5ce5038a202.png)

**Comment by aphex3k** [comment]
- bitcoind supports prune mode
- lnd supports prune mode
- electrs does not support prune mode
