### ISSUE TITLE
Please make Bitcoin RPC port available locally

### ISSUE THREAD

**Issue by esackbauer** [getumbrel/umbrel#506]
Currently docker exposes only port 8333 to local LAN. 
If RPC port 8332 would be exposed as well, we could configure Ledger Live to use the Umbrel node.

**Comment by lukechilds** [comment]
This is not really safe to do because RPC is not designed to be exposed. It's ok to expose with Tor because the hidden service provides enough entropy to be unguessable so it's essentially private.

If we expose it to the local network there are potential DoS attack vectors. It's also theoretically exposed remotely since any malicious website can make requests against `http://umbrel.local` which the browser will then resolve to your Umbrel over the local network.

Also imagine if you setup your laptop to connect Specter to Bitcoin Core RPC via umbrel.local. Then you went to a public space like a coffee shop and opened you laptop, Specter would broadcast your Bitcoin Core connection credentials in plain text over the coffee shop WiFi.

**Comment by esackbauer** [comment]
Thanks for the explanation, that is clearly a no-go.

**Comment by bepursuant** [comment]
I think this issue is worthy of further consideration. 

Bitcoin RPC has user authentication, does it not? If anything, it should be an **option** to enable RPC locally. For example, I stood up an umbrel node locally specifically so that I could do block chain analysis from another machine on my network, without having to run the node on that machine. From what I can see, there is no way to do this currently, as the decision has been made to not allow users to expose the RPC to the local network.

There is really no case in the world in which a software-based wallet like this should be housing **actual** keys that control actual bitcoin ownership, anyway. The risk is already sky-high, not allowing RPC on the local network isn't really a solution to much.

**Comment by unclemantis** [comment]
Bump

**Comment by AaronDewes** [comment]
> Bitcoin RPC has user authentication, does it not?

It has, but have you read Luke's comment above?

> Also imagine if you setup your laptop to connect Specter to Bitcoin Core RPC via umbrel.local. Then you went to a public space like a coffee shop and opened you laptop, Specter would broadcast your Bitcoin Core connection credentials in plain text over the coffee shop WiFi.

If you have your laptop anywhere else, Specter would send these credentials to any device called umbrel.local.

> If anything, it should be an option to enable RPC locally. 

This could still be added in the future.

**Comment by unclemantis** [comment]
I would like this availability..I run Umbrel on a RP4 through my local
network.

**Comment by hdutra** [comment]
Why it isn't configurable by environment variable or something like that?

**Comment by suchdatums** [comment]
> I stood up an umbrel node locally specifically so that I could do block chain analysis from another machine on my network, without having to run the node on that machine. From what I can see, there is no way to do this currently, as the decision has been made to not allow users to expose the RPC to the local network.

Same.  I'm going to change node software today because Umbrel isn't meeting my needs.

**Comment by sandipndev** [comment]
It would actually be helpful to have something like this.

**Comment by esackbauer** [comment]
It is already available in the latest version 0.5.0. Go to Bitcoin node, click on connect and select "RPC (local network)".
However I couldnt get it to run with Ledgers Live Wallet.

**Comment by unclemantis** [comment]
I killed my SSD months ago. I am not sure if it was because of a power outage that lasted longer than my UPS or the installation of a 3rd party blockchain node known as CHIA.

Once I get back in the saddle I really would like to have this feature open so that I can connect to Umbrel for use in a Stacks Blockchain Node / API Server on a separate Pi connected to the same router as the umbrel bitcoin node.

**Comment by calm108** [comment]
Any change on this or update? I am running the latest version and use the credential provided via the BTC Core Node Connect: RPC local but still can't connect ledger live nor can I explore a transaction using PS from another machine.

**Comment by pox** [comment]
Is this actually still true (8332 not exposed)?

```sh
root@umbrel:/home/umbrel# docker ps | grep 8332
5634d417a885   lncm/bitcoind:v27.0                              "bitcoind -port=8333…"     2 weeks ago   Up 2 weeks   8080/tcp, 18332-18333/tcp, 18443-18444/tcp, 28332-28333/tcp, 0.0.0.0:8332-8333->8332-8333/tcp, :::8332-8333->8332-8333/tcp            bitcoin_bitcoind_1
```

Seems to be exposed, yet Liana fails to connect to a node running in the same network over RPC... :/

`nc -z` from the Liana machine to Umbrel succeeds FWIW.
