### ISSUE TITLE
"Open" button, post install for Samourai Server and Mempool apps don't work.

### ISSUE THREAD

**Issue by StevenBlack** [getumbrel/umbrel#539]
This applies to the new **Samourai Server** and **Mempool** apps in Umbrel version 0.3.3,

* Immediately after installing both these apps, the screen looks something like this, with an inviting  "Open" button.

* If you click that button, right here, you get a non-resolving request page.

* However the apps both work if you go to the Apps page, and hit the respective app icons.

* **Note**: This button works if you first go to another Umbrel page, then use the browser Back button to return to this page.

**THEREFORE**, immediately post install, a state refresh on the page appears to be required, or the port listener in the app needs to be initiated.

**Observation**: the "Open" button feels a bit gratuitous.  It would be fine to just say "This App is ready to use in the Apps page" as opposed to providing an "Open" button right here.

**Edit**: using Chrome latest.

<img width="1331" alt="2021-02-15_10-58-46" src="https://user-images.githubusercontent.com/80144/107968974-13e06400-6f7d-11eb-95f0-09d3b065fee0.png">

**Comment by mayankchhabra** [comment]
Thanks for the report, @StevenBlack. It's due to the fact that both Samourai Server and Mempool take a few seconds to actually spin up their web servers, so their web servers are not immediately resolvable on their ports after installation. If you wait for a few seconds after the "Open" button shows up, you'll notice that they'll open fine. It's a minor annoyance for now, I agree, but not really worth writing a custom run-check logic.
