### ISSUE TITLE
"Not allowed by CORS" on dashboard

### ISSUE THREAD

**Issue by vVdLII8WbUien** [getumbrel/umbrel#584]
I tried using 
```sh
sudo NGINX_PORT=8000 ./scripts/start
```
But got a snackbar error "Not allowed by CORS".

My fix was changing "scripts/start" from:
```sh
DEVICE_IP="$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')"
```
to this
```sh
DEVICE_IP="$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'):$NGINX_PORT"
```

**Comment by louneskmt** [comment]
From what url are you accessing the dashboard?

**Comment by vVdLII8WbUien** [comment]
http://192.168.178.18:8000/dashboard

**Comment by phenomeus** [comment]
try this: https://github.com/getumbrel/umbrel/issues/398#issuecomment-782348577

**Comment by phenomeus** [comment]
with 0.3.6. and also port 8000 I hadn't to edit this anymore.

**Comment by MaikB85** [comment]
I still need to do the workaround from @vVdLII8WbUien after every update of Umbrel to get it running correctly. Otherwise bitcoin and lnd only show loading animation and no balance is visible.
I run Umbrel on a virtual machine with ubuntu. I need to run it on different port because other software use standard port of Umbrel.

Maybe someone can fix this issue? That would be nice.

**Comment by nmfretz** [comment]
closing old support issue
