### ISSUE TITLE
Inital sync has slowed to a crawl

### ISSUE THREAD

**Issue by veebch** [getumbrel/umbrel#588]
Hi there,

I'm really enjoying Umbrel..... I have a question though:

Running latest version: 0.3.6

Rpi 4 with SSD, was working its way through the initial sync nicely 10-15%/day. It has now slowed to about 1% a day. The processor also seems to be working less hard (less heat, low voltage on core, hash rate: 31EH/s)

Is this typical? Friends with similar umbrel setups are seeing much faster sync times. (I am using a 3A power supply and the syslog shows no complaints about being under voltage also there are no signs of throttling) 

Any ideas as to what could be causing this slowdown?

**Comment by sean-lloyd** [comment]
I'm new to Umbrel but with the previous initial syncs I've done with Bitcoin Core, progress slows down because the blocks get larger. The first 100,000 blocks will load much faster than the last 100,000 blocks because the early blocks had a handful of transactions and the later blocks were full. The progress may be calculated on X of Y blocks ... not X of Y bytes.

That said, my initial sync on Umbrel has been extremely slow due to instability over the last few days. I haven't had time to troubleshoot ... maybe it's a hardware issue, maybe Tor.

**Comment by llvllch** [comment]
They switched to bytes rather than blocks, I think

**Comment by KaffeMedFika** [comment]
I have the same problem, I am running a pi 4 4gb and started to sync a week ago. Now it goes crazy slow. I also have a flirc case so the temp should not be a problem. Is this normal? I have a 100 mbit download speed.

**Comment by KaffeMedFika** [comment]
I restarted my node 2 days ago and the speed is better now. The classic problem with just turning it off and on :D

**Comment by nmfretz** [comment]
closing old support issue
