### ISSUE TITLE
BTCPay LND access setting broken, requires manual configuration

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#608]
When activating lightning, it asks for my request string, which we already have set in the ENV of the docker.

Workaround:

Run the following command in the umbrel box, then copy paste the string to the LND setup page inside BTCPay.

```bash
$ docker exec btcpay-server_web_1 sh -c 'echo $BTCPAY_BTCLIGHTNING'
type=lnd-rest;server=https://xxx.xxx.xxx.xxx:8080/;macaroonfilepath=/lnd/data/chain/bitcoin/mainnet/admin.macaroon;allowinsecure=true
```

Similar to #607 in that the ENV of the docker-compose file shows effort to set the settings, but it seems they don't stick to the BTCPay instance for some reason.

**Comment by louneskmt** [comment]
This env var is set here: https://github.com/getumbrel/umbrel/blob/4c6c1c0acb5e95bfd6db2b7da1eaeb133d449487/apps/btcpay-server/docker-compose.yml#L57

The user just net to go setup LND, and instead of entering a string in the field, click on "Use internal LND" (or something like that, I don't recall the exact sentence), and it will automatically use the string set in this env var.

**Comment by junderw** [comment]
ok, this is just a confusing UI for BTCPay.
