### ISSUE TITLE
v3 onion service client authorization

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#715]
I'd like to tighten the security screws even more on the onion service for the dashboard.

This is possible with v3 onion service client authorization

https://community.torproject.org/onion-services/advanced/client-auth/

Any plan to add this? This would allow me to give multiple users access to the dashboard, each with its own authorization,
and I'm thinking this means I would not even have to give the god-mode password to any one of them.

This would also prevent opportunistic vulnerability scans (and getting listed on shodan, ishidan, insert-your-dan-here).

**Comment by lukechilds** [comment]
Thanks for the suggestion! The thing with Tor client auth is that the UX is pretty bad and confusing, especially for non-technical users. We could support it at some point in the future but we'd likely need to have our own Umbrel client app implemented first that can sets this all up automatically for the user. It's probably not something we'll implement soon during beta.

>This would allow me to give multiple users access to the dashboard, each with its own authorization,
and I'm thinking this means I would not even have to give the god-mode password to any one of them.

This would probably be better off implemented in a way that Umbrel is aware of, like multi user accounts, as opposed to relying on Tor for transparent multi user auth and Umbrel not knowing who is accessing it.

>This would also prevent opportunistic vulnerability scans (and getting listed on shodan, ishidan, insert-your-dan-here).

Can you clarify what you mean by "opportunistic vulnerability scans"? You mean someone guessing the hidden service address? If so, that's not a concern, a v3 hidden service has 256 bits of entropy, it's not possible to brute force.

Also, I'm not sure if you're aware, but assuming you haven't shared the hidden service with anyone else, there is effectively no difference in security between a HS with client auth enabled or disabled, since the knowledge of the high entropy hidden service address itself is essentially acting as an auth token. That said, assuming the address has not been shared is not a great assumption to work under, users could easily accidentally leak their hidden service address in a screenshot or share it without realising it's supposed to kept private. In these circumstances the dashboard password acts as a second line of defense. But I agree adding client auth would be a nice way to add additional protection in these rare circumstances.

>Any plan to add this?

So to answer your question, yes I imagine we would implement this at some point, but it's not high priority and not something I would consider critical while Umbrel is in beta.

**Comment by lestephane** [comment]
(i may repeat myself, but i think it bears repeating)

I see we're in agreement. I had to deploy a service with client auth on a VPS with the requirement to make it truly hidden, even to someone with the onion service address. Only client authorization can do that.

It's a bit like the passphrase for HD Wallets. It makes the service **actually** hidden, not **presumably** hidden.

So I have to insist that client authorization is important. Because non tech users (attracted without any doubt by your beautiful, easy to use UI),  will leak the onion address / URL of their umbrel without client auth. It's going to happen.

Adding a fine grained ACL at the level of  the web app is not going to help with preventing vulnerability scans for someone you obtained the leaked onion address / URL of an umbrel without client auth.

You want to make the service **actually** hidden to anyone but the users (family members?) you've added. They should not even be able to see that umbrel is running there without having the authorization.

**Comment by lestephane** [comment]
FWIW, UX for this is extremely hard to do right, I agree. I don't expect this fixed anytime soon, this issue may stay open for a loooog time. But at least we'll have it on the radar.

**Comment by AaronDewes** [comment]
> So I have to insist that client authorization is important. Because non tech users (attracted without any doubt by your beautiful, easy to use UI), will leak the onion address / URL of their umbrel without client auth. It's going to happen.

**So to answer your question, yes I imagine we would implement this at some point, but it's not high priority and not something I would consider critical while Umbrel is in beta.**

> Adding a fine grained ACL at the level of the web app is not going to help with preventing vulnerability scans for someone who obtained the leaked onion address / URL of an umbrel without client auth.

There is exactly 1 port open on the onion URL, and any vulnerability could be exploited over the local network too (although that's less likely). 

But I agree with you, for security purposes, this should be added in the future and very likely will be added.

**Comment by lukechilds** [comment]
Yeah, agree 1005 @lestephane.

**Comment by blastshielddown** [comment]
Related: Why does every app come with a hidden service by default? I can see why a user might want certain apps available over tor but it might be safer to enable no external services by default. If a user wants that capability, however, they could optionally enable it per app. I may be missing the intention behind the current design so would like to better understand the motivation.

**Comment by lukechilds** [comment]
The apps all have a hidden service by default because if you access the Umbrel web UI over Tor, when you click on an installed app icon it's web UI is opened in a new tab via it's Tor hidden service, otherwise they wouldn't be accessible.

Many Umbrel users are not technical and don't really understand what Tor is. They just know they download Tor Browser and paste in a special link and then everything works remotely. Giving them the option to enable/disable Tor on a per app basis would probably just add confusion for little benefit. There's practically no risk to have a hidden service running if you aren't actively using it.

Tor hidden services have 256bits of entropy, so if you don't use the hidden service, and don't share the link with anyone else, it's like it doesn't exist. It's not like having a service listening on a port on clearnet where it's open to any other device on the internet to ping it. If no one has knowledge of the Tor hidden service address, it's essentially private.

**Comment by lukechilds** [comment]
There isn't a simple way to do that currently. You could delete the specific entries in the Tor configuration file for each app you want to disable and restart Umbrel, but this change would be reverted each time you do an Umbrel update. You'd need to remember to go back and delete them again.
