### ISSUE TITLE
Allow i2p connections by default

### ISSUE THREAD

**Issue by dunxen** [getumbrel/umbrel#810]
Hey team! ☂️ 

It may be good to include an i2p daemon (such as `[i2pd](https://github.com/PurpleI2P/i2pd)`) and have the `bitcoin.conf` include i2p config by default (as it is replaced on every update). Since there are many umbrel users, this may help improve i2p connectivity across the network.

Relevant stack exchange answer: https://bitcoin.stackexchange.com/questions/103402/how-can-i-use-bitcoin-core-with-the-anonymous-network-protocol-i2p

**Comment by AaronDewes** [comment]
See also https://github.com/getumbrel/umbrel/issues/694.

While I2P is a good idea, I think tor is enough for now, and the base Umbrel install should not include too many tools. But maybe this can be in the app store once we extend the app framework.

**Comment by duncandean** [comment]
Thanks, I understand wanting to keep the base functionality with fewer tools. An app would be great once the framework is extended.

**Comment by xanoni** [comment]
Would be trivial to add, no different from Tor. And I can confirm that it is picking up, around one third of my peers are I2P peers. A few months ago it was maybe 1 or 2.

**Comment by count-null** [comment]
@AaronDewes Just wanting to revive this discussion in light of recent events. The UX of using tor to access node services has been degrading. I often have to wait multiple minutes or experience network timeouts due to Tor's increasing network congestion. 

Bitcoin core has enabled I2P support over 1-year ago. And there is a proposal in LND to [enable multiple proxies alongside Tor](https://github.com/lightningnetwork/lnd/issues/6845). There seems to be community support around the idea: [see this stacker news post](https://stacker.news/items/60428)

I'm hearing more node operators electing to abandon Tor-only due to these issues. In a time when online privacy is under attack, it feels like allowing multiple anonymity networks should be a priority.

**Comment by dunxen** [comment]
@count-null, he doesn't work on this project anymore, but yeah now is a good time to consider i2p

**Comment by nmfretz** [comment]
For those that find their way to this old issue, I2P connections are enabled by default now in the Bitcoin Node app. You can toggle this on and off in `Advanced Settings`
