### ISSUE TITLE
Allow the storing of the bitcoind chainstate and index folders on the SD card

### ISSUE THREAD

**Issue by hiddely** [getumbrel/umbrel#881]
Syncing is very slow (more than 3 months) on an Umbrel node with HDD, presumably due to the slow r/w performance of the HDD. A common optimization for this issue in other bitcoin nodes is to put the `index` and the `chainstate` folders on the faster SD card (for example through a symlink). However, the use of docker volumes prevents the efficient use of symlinks.

Would it be possible to add this functionality to Umbrel in some way?

**Comment by juscamarena** [comment]
You'd destroy your SD card pretty fast no?

**Comment by lukechilds** [comment]
Some SD cards may be faster than an HDD (although many will be much slower) but the real issue is reliability. Heavy write workloads on an SD card wear them out pretty fast. We've actually gone to great lengths to ensure the SD card is used as little as possible on Umbrel, we bind mount things like the swapfile and Docker data dir on to the external drive, so they aren't wearing out the SD card.

This isn't something we'd want to add support for due to the reliability issues it would cause.

We strongly recommend using an SSD as the external storage device, not only will it be much faster than an HDD, it'll also use less power which reduces the chance of overloading the Pi's power supply circuitry which can also cause stability issues.
